In [56]:
import numpy as np
import pandas as p
import matplotlib.pyplot as plt

In [57]:
Data = p.read_csv('../data/bestsellers.csv')
dataset = Data
dataset

,Name,Author,User Rating,Reviews,Price,Year,Genre
0,10-Day Green Smoothie Cleanse,JJ Smith,4.7,17350.0,8.0,2016,Non Fiction
1,11/22/63: A Novel,Stephen King,4.6,2052.0,22.0,2011,Fiction
2,12 Rules for Life: An Antidote to Chaos,Jordan B. Peterson,4.7,18979.0,15.0,2018,Non Fiction
3,1984 (Signet Classics),George Orwell,4.7,21424.0,6.0,2017,Fiction
4,"5,000 Awesome Facts (About Everything!) (Natio...",National Geographic Kids,4.8,7665.0,12.0,2019,Non Fiction
...,...,...,...,...,...,...,...
545,Wrecking Ball (Diary of a Wimpy Kid Book 14),Jeff Kinney,4.9,9413.0,8.0,2019,Fiction
546,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2016,Non Fiction
547,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2017,Non Fiction
548,You Are a Badass: How to Stop Doubting Your Gr...,Jen Sincero,4.7,14331.0,8.0,2018,Non Fiction


In [58]:
dataset.dtypes

Name               str
Author             str
User Rating    float64
Reviews        float64
Price          float64
Year             int64
Genre              str
dtype: object

In [59]:
dataset.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='str')

In [60]:
dataset.info()

<class 'pandas.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    str    
 1   Author       550 non-null    str    
 2   User Rating  548 non-null    float64
 3   Reviews      549 non-null    float64
 4   Price        549 non-null    float64
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    str    
dtypes: float64(3), int64(1), str(3)
memory usage: 30.2 KB


In [61]:
dataset.describe()

,User Rating,Reviews,Price,Year
count,548.000000,549.000000,549.000000,550.000000
mean,4.618066,11958.038251,13.100182,2014.000000
std,0.227341,11741.299889,10.852149,3.165156
min,3.300000,37.000000,0.000000,2009.000000
25%,4.500000,4028.000000,7.000000,2011.000000
50%,4.700000,8580.000000,11.000000,2014.000000
75%,4.800000,17323.000000,16.000000,2017.000000
max,4.900000,87841.000000,105.000000,2019.000000


In [62]:
dataset.isnull().sum()

Name           0
Author         0
User Rating    2
Reviews        1
Price          1
Year           0
Genre          0
dtype: int64

In [63]:
dataset.duplicated().sum()

np.int64(0)

In [64]:
dataset
x=dataset.iloc[:, :-1].values
x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019]],
      shape=(550, 6), dtype=object)

In [65]:
y = dataset.iloc[:, 3].values
y

array([1.7350e+04, 2.0520e+03, 1.8979e+04, 2.1424e+04, 7.6650e+03,
       1.2643e+04, 1.9735e+04, 1.9699e+04, 5.9830e+03, 2.3848e+04,
       2.3848e+04, 4.6000e+02, 4.1490e+03, 5.1530e+03, 5.0130e+03,
       2.3130e+03, 2.9250e+03, 2.9510e+03, 2.4260e+03, 9.1980e+03,
       3.6348e+04, 3.6348e+04, 6.3100e+03, 1.5921e+04, 1.2159e+04,
       7.9800e+02, 9.3740e+03, 4.9100e+02, 5.3600e+03, 1.9090e+03,
       1.2960e+03, 6.1500e+02, 6.1133e+04, 6.1133e+04, 1.1113e+04,
       1.0070e+04, 1.0070e+04, 3.7290e+03, 9.7690e+03, 4.7100e+02,
       1.4344e+04, 1.4344e+04, 4.5050e+03, 1.0369e+04, 1.6244e+04,
       2.8840e+03, 2.2614e+04, 2.2614e+04, 2.2614e+04, 4.7610e+03,
       1.5420e+03, 1.5420e+03, 1.5420e+03, 6.1430e+03, 4.0220e+03,
       3.8710e+03, 4.8660e+03, 4.8660e+03, 1.3290e+03, 4.6420e+03,
       1.5410e+03, 1.9240e+03, 2.0940e+03, 1.0922e+04, 1.0922e+04,
       1.0922e+04, 1.0922e+04, 2.1370e+03, 1.6510e+03, 6.6790e+03,
       6.6790e+03, 6.8120e+03, 3.8370e+03, 6.5400e+03, 7.9550e

In [66]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='mean')

imputer = imputer.fit(x[:, 2:6])
x[:, 2:6] = imputer.transform(x[:, 2:6])

x

array([['10-Day Green Smoothie Cleanse', 'JJ Smith', 4.7, 17350.0, 8.0,
        2016.0],
       ['11/22/63: A Novel', 'Stephen King', 4.6, 2052.0, 22.0, 2011.0],
       ['12 Rules for Life: An Antidote to Chaos', 'Jordan B. Peterson',
        4.7, 18979.0, 15.0, 2018.0],
       ...,
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2017.0],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2018.0],
       ['You Are a Badass: How to Stop Doubting Your Greatness and Start Living an Awesome Life',
        'Jen Sincero', 4.7, 14331.0, 8.0, 2019.0]],
      shape=(550, 6), dtype=object)

In [67]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_x = LabelEncoder()
x[:, 0] = labelencoder_x.fit_transform(x[:, 0])
print(x)

[[0 'JJ Smith' 4.7 17350.0 8.0 2016.0]
 [1 'Stephen King' 4.6 2052.0 22.0 2011.0]
 [2 'Jordan B. Peterson' 4.7 18979.0 15.0 2018.0]
 ...
 [350 'Jen Sincero' 4.7 14331.0 8.0 2017.0]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2018.0]
 [350 'Jen Sincero' 4.7 14331.0 8.0 2019.0]]


In [68]:
labelenc_y = LabelEncoder()
y = labelenc_y.fit_transform(y)
y

array([291,  52, 296, 304, 196, 267, 302, 300, 163, 318, 318,   5, 113,
       139, 135,  61,  75,  77,  63, 221, 337, 337, 171, 284, 264,  12,
       228,   7, 146,  47,  23,   9, 343, 343, 256, 240, 240,  99, 233,
         6, 278, 278, 118, 245, 285,  74, 310, 310, 310, 130,  32,  32,
        32, 167, 110, 108, 133, 133,  26, 126,  31,  48,  54, 252, 252,
       252, 252,  57,  37, 177, 177, 179, 107, 174, 204, 327, 327, 292,
         0, 283,  82, 136, 131, 188, 188, 266, 220, 149, 138,  56,  65,
        11,  16, 172, 172, 153, 153, 329, 329, 148, 248, 248, 117, 164,
       317, 303, 339, 339, 275, 272, 290, 290, 290, 290, 290,  33,  97,
        21, 155, 155, 155,   2, 132, 276, 276, 276, 276, 276, 195, 308,
       308,  27, 280, 231,  35, 342, 342, 342, 242,  88,  88,  88,  88,
       214, 214, 214, 183, 183, 161, 322, 150, 158, 112, 299, 319, 198,
        80, 239,  94, 269,  49, 282, 282, 281, 281, 101, 320, 320, 320,
       320, 320, 143,  90,  90,  72, 134, 232,  25, 286, 286, 18

In [71]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct = ColumnTransformer(
    transformers=[
        ("categorical", OneHotEncoder(handle_unknown="ignore", sparse_output=False), [0, 1, 5])
    ],
    remainder="passthrough"
)

x = ct.fit_transform(x)

x

array([[1.0, 0.0, 0.0, ..., 4.7, 17350.0, 8.0],
       [0.0, 1.0, 0.0, ..., 4.6, 2052.0, 22.0],
       [0.0, 0.0, 1.0, ..., 4.7, 18979.0, 15.0],
       ...,
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.7, 14331.0, 8.0]],
      shape=(550, 613), dtype=object)

In [72]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 45)

In [73]:
x_test

array([[0.0, 0.0, 0.0, ..., 4.6, 19720.0, 8.0],
       [0.0, 0.0, 0.0, ..., 4.8, 29673.0, 16.0],
       [0.0, 0.0, 0.0, ..., 4.7, 10820.0, 5.0],
       ...,
       [0.0, 0.0, 0.0, ..., 4.7, 6377.0, 7.0],
       [0.0, 0.0, 0.0, ..., 4.8, 2091.0, 12.0],
       [0.0, 0.0, 0.0, ..., 4.3, 5272.0, 16.0]],
      shape=(110, 613), dtype=object)

In [74]:
x_test.astype(int)

array([[    0,     0,     0, ...,     4, 19720,     8],
       [    0,     0,     0, ...,     4, 29673,    16],
       [    0,     0,     0, ...,     4, 10820,     5],
       ...,
       [    0,     0,     0, ...,     4,  6377,     7],
       [    0,     0,     0, ...,     4,  2091,    12],
       [    0,     0,     0, ...,     4,  5272,    16]], shape=(110, 613))

In [75]:
from sklearn.preprocessing import StandardScaler

sc_x = StandardScaler()

x_train = sc_x.fit_transform(x_train)
x_test = sc_x.transform(x_test)

In [ ]:
x_train.astype(int)

array([[-1,  0,  1, -1, -1],
       [-1,  2,  0,  1,  1],
       [ 1,  0,  0,  0,  0],
       [-1,  0,  1,  0, -1],
       [ 1,  0,  0,  0,  0],
       [ 1,  0,  0,  1,  1],
       [ 1,  0,  0,  0,  0],
       [-1,  0,  1,  0,  0]])

In [76]:
x_test.astype(int)

array([[ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  1,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       ...,
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ...,  0,  0,  0],
       [ 0,  0,  0, ..., -1,  0,  0]], shape=(110, 613))